/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPermalink } from "./IPermalink";
export type { PermalinkMarketplace } from "./PermalinkMarketplace";
