/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as permalinkMarketplaceSol from "./PermalinkMarketplace.sol";
export { Permalink__factory } from "./Permalink__factory";
