/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPermalinkERC721 } from "./IPermalinkERC721";
export type { PermalinkMarketplace } from "./PermalinkMarketplace";
