/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPermalink__factory } from "./IPermalink__factory";
export { PermalinkMarketplace__factory } from "./PermalinkMarketplace__factory";
