/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPermalink,
  IPermalinkInterface,
} from "../../../../artifacts/contracts/PermalinkMarketplace.sol/IPermalink";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "salePrice",
        type: "uint256",
      },
    ],
    name: "getSecondaryFees",
    outputs: [
      {
        internalType: "address",
        name: "artist",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "artistRoyalty",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "platformFee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalFees",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPermalink__factory {
  static readonly abi = _abi;
  static createInterface(): IPermalinkInterface {
    return new Interface(_abi) as IPermalinkInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPermalink {
    return new Contract(address, _abi, runner) as unknown as IPermalink;
  }
}
