/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as permalinkMarketplaceSol from "./PermalinkMarketplace.sol";
export type { permalinkMarketplaceSol };
export type { Permalink } from "./Permalink";
