/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as permalinkErc721Sol from "./PermalinkERC721.sol";
export type { permalinkErc721Sol };
import type * as permalinkMarketplaceSol from "./PermalinkMarketplace.sol";
export type { permalinkMarketplaceSol };
import type * as permalinkMarketplaceErc721Sol from "./PermalinkMarketplaceERC721.sol";
export type { permalinkMarketplaceErc721Sol };
export type { Permalink } from "./Permalink";
