/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PermalinkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_PLATFORM_FEE"
      | "addAdmin"
      | "adminAddressList"
      | "adminAddresses"
      | "approveAddresses"
      | "artistProfiles"
      | "artistTokens"
      | "artworks"
      | "balanceOf"
      | "balanceOfBatch"
      | "collectorTokens"
      | "exists"
      | "getAdminAddresses"
      | "getArtistProfile"
      | "getArtistTokens"
      | "getArtwork"
      | "getArtworkImageData"
      | "getCollectorTokens"
      | "getCurrentTokenId"
      | "getInterestedAddresses"
      | "getSecondaryFees"
      | "getWhitelistedAddresses"
      | "interestedAddressList"
      | "interestedAddresses"
      | "isAdmin"
      | "isApprovedForAll"
      | "isInterested"
      | "isWhitelistEnabled"
      | "isWhitelisted"
      | "mintArtwork"
      | "name"
      | "owner"
      | "pause"
      | "paused"
      | "platformFeePercentage"
      | "purchaseArtwork"
      | "registerInterest"
      | "removeAdmin"
      | "removeFromWhitelist"
      | "renounceOwnership"
      | "royaltyInfo"
      | "safeBatchTransferFrom"
      | "safeTransferFrom"
      | "secondaryArtistRoyalty"
      | "secondaryPlatformFee"
      | "setApprovalForAll"
      | "setPlatformFee"
      | "setSecondaryFees"
      | "setTreasuryAddress"
      | "setURI"
      | "supportsInterface"
      | "symbol"
      | "toggleArtworkStatus"
      | "toggleWhitelist"
      | "tokenToArtist"
      | "totalSupply()"
      | "totalSupply(uint256)"
      | "transferOwnership"
      | "treasuryAddress"
      | "unpause"
      | "updateArtistProfile"
      | "updateArtworkPrice"
      | "uri"
      | "whitelistEnabled"
      | "whitelistedAddressList"
      | "whitelistedAddresses"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressRegisteredInterest"
      | "AddressRemovedFromWhitelist"
      | "AddressWhitelisted"
      | "AdminAdded"
      | "AdminRemoved"
      | "ApprovalForAll"
      | "ArtistProfileUpdated"
      | "ArtworkMinted"
      | "ArtworkPurchased"
      | "OwnershipTransferred"
      | "Paused"
      | "PlatformFeeUpdated"
      | "TransferBatch"
      | "TransferSingle"
      | "URI"
      | "Unpaused"
      | "WhitelistToggled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddressList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveAddresses",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "artistProfiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "artistTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "artworks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "collectorTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getArtistProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getArtistTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getArtwork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArtworkImageData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectorTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInterestedAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSecondaryFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelistedAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interestedAddressList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "interestedAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInterested",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintArtwork",
    values: [string, string, BytesLike, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseArtwork",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerInterest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "secondaryArtistRoyalty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "secondaryPlatformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecondaryFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setURI", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "toggleArtworkStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleWhitelist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToArtist",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateArtistProfile",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateArtworkPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "whitelistEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedAddressList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "artistProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "artistTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "artworks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectorTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAdminAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArtistProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArtistTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getArtwork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getArtworkImageData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectorTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInterestedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecondaryFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestedAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInterested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintArtwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseArtwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerInterest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "secondaryArtistRoyalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "secondaryPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSecondaryFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleArtworkStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenToArtist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateArtistProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateArtworkPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace AddressRegisteredInterestEvent {
  export type InputTuple = [addr: AddressLike];
  export type OutputTuple = [addr: string];
  export interface OutputObject {
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddressRemovedFromWhitelistEvent {
  export type InputTuple = [addr: AddressLike];
  export type OutputTuple = [addr: string];
  export interface OutputObject {
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddressWhitelistedEvent {
  export type InputTuple = [addr: AddressLike];
  export type OutputTuple = [addr: string];
  export interface OutputObject {
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminAddedEvent {
  export type InputTuple = [admin: AddressLike, addedBy: AddressLike];
  export type OutputTuple = [admin: string, addedBy: string];
  export interface OutputObject {
    admin: string;
    addedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRemovedEvent {
  export type InputTuple = [admin: AddressLike, removedBy: AddressLike];
  export type OutputTuple = [admin: string, removedBy: string];
  export interface OutputObject {
    admin: string;
    removedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    account: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    account: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    account: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArtistProfileUpdatedEvent {
  export type InputTuple = [
    artist: AddressLike,
    name: string,
    bio: string,
    avatarURI: string
  ];
  export type OutputTuple = [
    artist: string,
    name: string,
    bio: string,
    avatarURI: string
  ];
  export interface OutputObject {
    artist: string;
    name: string;
    bio: string;
    avatarURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArtworkMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    artist: AddressLike,
    title: string,
    price: BigNumberish,
    maxSupply: BigNumberish,
    imageSize: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    artist: string,
    title: string,
    price: bigint,
    maxSupply: bigint,
    imageSize: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    artist: string;
    title: string;
    price: bigint;
    maxSupply: bigint;
    imageSize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArtworkPurchasedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    buyer: AddressLike,
    artist: AddressLike,
    amount: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    buyer: string,
    artist: string,
    amount: bigint,
    price: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    buyer: string;
    artist: string;
    amount: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferBatchEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    ids: BigNumberish[],
    values: BigNumberish[]
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    ids: bigint[],
    values: bigint[]
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    ids: bigint[];
    values: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferSingleEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    id: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    id: bigint,
    value: bigint
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    id: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace URIEvent {
  export type InputTuple = [value: string, id: BigNumberish];
  export type OutputTuple = [value: string, id: bigint];
  export interface OutputObject {
    value: string;
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistToggledEvent {
  export type InputTuple = [enabled: boolean, toggledBy: AddressLike];
  export type OutputTuple = [enabled: boolean, toggledBy: string];
  export interface OutputObject {
    enabled: boolean;
    toggledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Permalink extends BaseContract {
  connect(runner?: ContractRunner | null): Permalink;
  waitForDeployment(): Promise<this>;

  interface: PermalinkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  addAdmin: TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  adminAddressList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  adminAddresses: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  approveAddresses: TypedContractMethod<
    [addresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  artistProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        name: string;
        bio: string;
        avatarURI: string;
        totalCreated: bigint;
        totalCollected: bigint;
        isRegistered: boolean;
      }
    ],
    "view"
  >;

  artistTokens: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  artworks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        tokenId: bigint;
        artist: string;
        title: string;
        description: string;
        imageData: string;
        imageType: string;
        price: bigint;
        maxSupply: bigint;
        currentSupply: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  balanceOf: TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;

  balanceOfBatch: TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;

  collectorTokens: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  exists: TypedContractMethod<[id: BigNumberish], [boolean], "view">;

  getAdminAddresses: TypedContractMethod<[], [string[]], "view">;

  getArtistProfile: TypedContractMethod<
    [artist: AddressLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        artistName: string;
        bio: string;
        avatarURI: string;
        totalCreated: bigint;
        totalCollected: bigint;
        isRegistered: boolean;
      }
    ],
    "view"
  >;

  getArtistTokens: TypedContractMethod<
    [artist: AddressLike],
    [bigint[]],
    "view"
  >;

  getArtwork: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        artist: string;
        title: string;
        description: string;
        imageType: string;
        imageSize: bigint;
        price: bigint;
        maxSupply: bigint;
        currentSupply: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getArtworkImageData: TypedContractMethod<
    [tokenId: BigNumberish],
    [[string, string] & { imageData: string; imageType: string }],
    "view"
  >;

  getCollectorTokens: TypedContractMethod<
    [collector: AddressLike],
    [bigint[]],
    "view"
  >;

  getCurrentTokenId: TypedContractMethod<[], [bigint], "view">;

  getInterestedAddresses: TypedContractMethod<[], [string[]], "view">;

  getSecondaryFees: TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        artist: string;
        artistRoyalty: bigint;
        platformFee: bigint;
        totalFees: bigint;
      }
    ],
    "view"
  >;

  getWhitelistedAddresses: TypedContractMethod<[], [string[]], "view">;

  interestedAddressList: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  interestedAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  isAdmin: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isApprovedForAll: TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  isInterested: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isWhitelistEnabled: TypedContractMethod<[], [boolean], "view">;

  isWhitelisted: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  mintArtwork: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _imageData: BytesLike,
      _imageType: string,
      _price: BigNumberish,
      _maxSupply: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFeePercentage: TypedContractMethod<[], [bigint], "view">;

  purchaseArtwork: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;

  registerInterest: TypedContractMethod<[], [void], "nonpayable">;

  removeAdmin: TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  removeFromWhitelist: TypedContractMethod<
    [addr: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  royaltyInfo: TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint] & { receiver: string; royaltyAmount: bigint }],
    "view"
  >;

  safeBatchTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  safeTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  secondaryArtistRoyalty: TypedContractMethod<[], [bigint], "view">;

  secondaryPlatformFee: TypedContractMethod<[], [bigint], "view">;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_platformFeePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSecondaryFees: TypedContractMethod<
    [_platformFee: BigNumberish, _artistRoyalty: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasuryAddress: TypedContractMethod<
    [_treasuryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setURI: TypedContractMethod<[newURI: string], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  toggleArtworkStatus: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  toggleWhitelist: TypedContractMethod<[], [void], "nonpayable">;

  tokenToArtist: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  "totalSupply()": TypedContractMethod<[], [bigint], "view">;

  "totalSupply(uint256)": TypedContractMethod<
    [id: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryAddress: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateArtistProfile: TypedContractMethod<
    [_name: string, _bio: string, _avatarURI: string],
    [void],
    "nonpayable"
  >;

  updateArtworkPrice: TypedContractMethod<
    [tokenId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  uri: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  whitelistEnabled: TypedContractMethod<[], [boolean], "view">;

  whitelistedAddressList: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  whitelistedAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  withdrawPlatformFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminAddressList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "adminAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "approveAddresses"
  ): TypedContractMethod<[addresses: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "artistProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        name: string;
        bio: string;
        avatarURI: string;
        totalCreated: bigint;
        totalCollected: bigint;
        isRegistered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "artistTokens"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "artworks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        tokenId: bigint;
        artist: string;
        title: string;
        description: string;
        imageData: string;
        imageType: string;
        price: bigint;
        maxSupply: bigint;
        currentSupply: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOfBatch"
  ): TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectorTokens"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "exists"
  ): TypedContractMethod<[id: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAdminAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getArtistProfile"
  ): TypedContractMethod<
    [artist: AddressLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        artistName: string;
        bio: string;
        avatarURI: string;
        totalCreated: bigint;
        totalCollected: bigint;
        isRegistered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getArtistTokens"
  ): TypedContractMethod<[artist: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getArtwork"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        artist: string;
        title: string;
        description: string;
        imageType: string;
        imageSize: bigint;
        price: bigint;
        maxSupply: bigint;
        currentSupply: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getArtworkImageData"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [[string, string] & { imageData: string; imageType: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCollectorTokens"
  ): TypedContractMethod<[collector: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCurrentTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getInterestedAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSecondaryFees"
  ): TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        artist: string;
        artistRoyalty: bigint;
        platformFee: bigint;
        totalFees: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWhitelistedAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "interestedAddressList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "interestedAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isInterested"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelistEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintArtwork"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _imageData: BytesLike,
      _imageType: string,
      _price: BigNumberish,
      _maxSupply: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseArtwork"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registerInterest"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeFromWhitelist"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "royaltyInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint] & { receiver: string; royaltyAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeBatchTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "secondaryArtistRoyalty"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "secondaryPlatformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<
    [_platformFeePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSecondaryFees"
  ): TypedContractMethod<
    [_platformFee: BigNumberish, _artistRoyalty: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasuryAddress"
  ): TypedContractMethod<[_treasuryAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setURI"
  ): TypedContractMethod<[newURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "toggleArtworkStatus"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleWhitelist"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenToArtist"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply(uint256)"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateArtistProfile"
  ): TypedContractMethod<
    [_name: string, _bio: string, _avatarURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateArtworkPrice"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uri"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "whitelistEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistedAddressList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "whitelistedAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AddressRegisteredInterest"
  ): TypedContractEvent<
    AddressRegisteredInterestEvent.InputTuple,
    AddressRegisteredInterestEvent.OutputTuple,
    AddressRegisteredInterestEvent.OutputObject
  >;
  getEvent(
    key: "AddressRemovedFromWhitelist"
  ): TypedContractEvent<
    AddressRemovedFromWhitelistEvent.InputTuple,
    AddressRemovedFromWhitelistEvent.OutputTuple,
    AddressRemovedFromWhitelistEvent.OutputObject
  >;
  getEvent(
    key: "AddressWhitelisted"
  ): TypedContractEvent<
    AddressWhitelistedEvent.InputTuple,
    AddressWhitelistedEvent.OutputTuple,
    AddressWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRemoved"
  ): TypedContractEvent<
    AdminRemovedEvent.InputTuple,
    AdminRemovedEvent.OutputTuple,
    AdminRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "ArtistProfileUpdated"
  ): TypedContractEvent<
    ArtistProfileUpdatedEvent.InputTuple,
    ArtistProfileUpdatedEvent.OutputTuple,
    ArtistProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ArtworkMinted"
  ): TypedContractEvent<
    ArtworkMintedEvent.InputTuple,
    ArtworkMintedEvent.OutputTuple,
    ArtworkMintedEvent.OutputObject
  >;
  getEvent(
    key: "ArtworkPurchased"
  ): TypedContractEvent<
    ArtworkPurchasedEvent.InputTuple,
    ArtworkPurchasedEvent.OutputTuple,
    ArtworkPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferBatch"
  ): TypedContractEvent<
    TransferBatchEvent.InputTuple,
    TransferBatchEvent.OutputTuple,
    TransferBatchEvent.OutputObject
  >;
  getEvent(
    key: "TransferSingle"
  ): TypedContractEvent<
    TransferSingleEvent.InputTuple,
    TransferSingleEvent.OutputTuple,
    TransferSingleEvent.OutputObject
  >;
  getEvent(
    key: "URI"
  ): TypedContractEvent<
    URIEvent.InputTuple,
    URIEvent.OutputTuple,
    URIEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistToggled"
  ): TypedContractEvent<
    WhitelistToggledEvent.InputTuple,
    WhitelistToggledEvent.OutputTuple,
    WhitelistToggledEvent.OutputObject
  >;

  filters: {
    "AddressRegisteredInterest(address)": TypedContractEvent<
      AddressRegisteredInterestEvent.InputTuple,
      AddressRegisteredInterestEvent.OutputTuple,
      AddressRegisteredInterestEvent.OutputObject
    >;
    AddressRegisteredInterest: TypedContractEvent<
      AddressRegisteredInterestEvent.InputTuple,
      AddressRegisteredInterestEvent.OutputTuple,
      AddressRegisteredInterestEvent.OutputObject
    >;

    "AddressRemovedFromWhitelist(address)": TypedContractEvent<
      AddressRemovedFromWhitelistEvent.InputTuple,
      AddressRemovedFromWhitelistEvent.OutputTuple,
      AddressRemovedFromWhitelistEvent.OutputObject
    >;
    AddressRemovedFromWhitelist: TypedContractEvent<
      AddressRemovedFromWhitelistEvent.InputTuple,
      AddressRemovedFromWhitelistEvent.OutputTuple,
      AddressRemovedFromWhitelistEvent.OutputObject
    >;

    "AddressWhitelisted(address)": TypedContractEvent<
      AddressWhitelistedEvent.InputTuple,
      AddressWhitelistedEvent.OutputTuple,
      AddressWhitelistedEvent.OutputObject
    >;
    AddressWhitelisted: TypedContractEvent<
      AddressWhitelistedEvent.InputTuple,
      AddressWhitelistedEvent.OutputTuple,
      AddressWhitelistedEvent.OutputObject
    >;

    "AdminAdded(address,address)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminRemoved(address,address)": TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;
    AdminRemoved: TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "ArtistProfileUpdated(address,string,string,string)": TypedContractEvent<
      ArtistProfileUpdatedEvent.InputTuple,
      ArtistProfileUpdatedEvent.OutputTuple,
      ArtistProfileUpdatedEvent.OutputObject
    >;
    ArtistProfileUpdated: TypedContractEvent<
      ArtistProfileUpdatedEvent.InputTuple,
      ArtistProfileUpdatedEvent.OutputTuple,
      ArtistProfileUpdatedEvent.OutputObject
    >;

    "ArtworkMinted(uint256,address,string,uint256,uint256,uint256)": TypedContractEvent<
      ArtworkMintedEvent.InputTuple,
      ArtworkMintedEvent.OutputTuple,
      ArtworkMintedEvent.OutputObject
    >;
    ArtworkMinted: TypedContractEvent<
      ArtworkMintedEvent.InputTuple,
      ArtworkMintedEvent.OutputTuple,
      ArtworkMintedEvent.OutputObject
    >;

    "ArtworkPurchased(uint256,address,address,uint256,uint256)": TypedContractEvent<
      ArtworkPurchasedEvent.InputTuple,
      ArtworkPurchasedEvent.OutputTuple,
      ArtworkPurchasedEvent.OutputObject
    >;
    ArtworkPurchased: TypedContractEvent<
      ArtworkPurchasedEvent.InputTuple,
      ArtworkPurchasedEvent.OutputTuple,
      ArtworkPurchasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "TransferBatch(address,address,address,uint256[],uint256[])": TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;
    TransferBatch: TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;

    "TransferSingle(address,address,address,uint256,uint256)": TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;
    TransferSingle: TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;

    "URI(string,uint256)": TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;
    URI: TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WhitelistToggled(bool,address)": TypedContractEvent<
      WhitelistToggledEvent.InputTuple,
      WhitelistToggledEvent.OutputTuple,
      WhitelistToggledEvent.OutputObject
    >;
    WhitelistToggled: TypedContractEvent<
      WhitelistToggledEvent.InputTuple,
      WhitelistToggledEvent.OutputTuple,
      WhitelistToggledEvent.OutputObject
    >;
  };
}
