/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPermalinkERC721,
  IPermalinkERC721Interface,
} from "../../../../artifacts/contracts/PermalinkMarketplaceERC721.sol/IPermalinkERC721";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getIndividualArtwork",
    outputs: [
      {
        internalType: "uint256",
        name: "seriesId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "artist",
        type: "address",
      },
      {
        internalType: "string",
        name: "title",
        type: "string",
      },
      {
        internalType: "string",
        name: "description",
        type: "string",
      },
      {
        internalType: "string",
        name: "imageType",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "imageSize",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mintedAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "salePrice",
        type: "uint256",
      },
    ],
    name: "getSecondaryFees",
    outputs: [
      {
        internalType: "address",
        name: "artist",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "artistRoyalty",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "platformFee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalFees",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPermalinkERC721__factory {
  static readonly abi = _abi;
  static createInterface(): IPermalinkERC721Interface {
    return new Interface(_abi) as IPermalinkERC721Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPermalinkERC721 {
    return new Contract(address, _abi, runner) as unknown as IPermalinkERC721;
  }
}
